import 'package:flutter/material.dart';
import 'package:flutter_sqlite/customcard.dart';
class MssgList{
  List<Widget> mssgList=[
    Container(
      margin: EdgeInsets.only(left: 20,top: 10,bottom: 10),
      child: Text('Today',style: TextStyle(
        fontSize: 15,
        fontWeight: FontWeight.w500,
        color: Colors.black87,


      ) ,),
    ),

    CustomCard(picture: NetworkImage('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRiXYxCDrbU2zCOgiQNkyDpZ7jyvPwoSdHvxA&usqp=CAU'),
      title:'Brunch this weekend?',
      name:'Ali Connors',
      message: 'hello everyone',
      time:'10:00',),
    Divider(height: 3,
      thickness: 2,
      indent: 90,
    ),
    CustomCard(picture: NetworkImage('https://upload.wikimedia.org/wikipedia/commons/e/e8/Chris_Hemsworth_by_Gage_Skidmore_2_%28cropped%29.jpg'),
      title:'Official group',
      name:'Madam',
      message: 'submit by tonight',
      time:'9:28',),
    Divider(height: 3,
        thickness: 2,
        indent: 90),
    CustomCard(picture: NetworkImage('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT69kbCChTRUqPnkdO1b-Fd7i0ijHWI1R9SCA&usqp=CAU'),
      title:'Goa plan',
      name:'Senior',
      message: 'Dont back out',
      time:'9:25',),
    Divider(height: 3,
        thickness: 2,
        indent: 90),
    CustomCard(picture: NetworkImage('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsUP3WL00_89fUMvmM9qmY3fbUZKDzNQpSDA&usqp=CAU'),
      title:'Temple',
      name:'Swamy',
      message: 'Jai Hanuman',
      time:'9:20',),
    Divider(height: 3,
        thickness: 2,
        indent: 90),CustomCard(picture: NetworkImage('https://m.media-amazon.com/images/M/MV5BMTg1NjE3NDcxMF5BMl5BanBnXkFtZTYwODU1Njg2._V1_.jpg'),
      title:'Fight Club',
      name:'Taylor Durden',
      message: 'First rule of fight club',
      time:'10:00',),
    Divider(height: 3,
      thickness: 2,
      indent: 90,),
    CustomCard(picture: NetworkImage('https://i.pinimg.com/originals/14/fc/18/14fc18aad800d685c4ddb729560c549a.jpg'),
      title:'Devotional',
      name:'Anji',
      message: 'Fast this Tuesday',
      time:'10:00'),
    Divider(height: 3,
      thickness: 2,
      indent: 90),
    CustomCard(picture: NetworkImage('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFcLatb6NU0y5H_mWdgAoCz1QLbpyTMS2Xug&usqp=CAU'),
        title:'Lets raid west',
        name:'Ragnor Lothbrok',
        message: 'prepare the ships',
        time:'10:00'),
    Divider(height: 3,
        thickness: 2,
        indent: 90),
    CustomCard(picture: NetworkImage('https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRnqjGfdB0T_x0XKYi5CxlxFJ8PEE-MAeFSKw&usqp=CAU'),
        title:'The Vampires',
        name:'Damon',
        message: 'Big bad vamp out here',
        time:'10:00'),
    Divider(height: 3,
        thickness: 2,
        indent: 90),
  ];

}